---
- name: Install with yum and apt
  hosts: planetexpress
  gather_facts: yes

  vars:
          aptlist:
                  - sl
                  - bastet
                  - moon-buggy
                  - ninvaders
          yumlist:
                  - sl
                  - moon-buggy          


  tasks:
          - name: install with apt
            apt:
                    name: "{{ aptlist }}" 
                    state: present
            become: yes
            when: ansible_os_family == "Debian"

          - name: install with yum
            yum: 
                   name: "{{ yumlist }}"
                   state: present
            become: yes          
            when: ansible_os_family=="RedHat"
