---
- name: Using ansible to call python code
  gather_facts: yes
  hosts: localhost

  tasks: 
         - name: call my python script
           script: ~/ans/scripts/parselog.py
           args:
              executable: python3
           register: results

         - debug: 
            var: results.stdout



