---
- name: Understanding playbook execution
  gather_facts: yes
  hosts: example

  pre_tasks:
          ## I execute first
          # then any handlers called will execute
   - name: call my py script that normalizes data used for the role
     script:
             ## call python script that reads from excel, csv, email

  roles:
          ## 

  tasks:
          - import role
          - inclue role


  post_tasks:

  handlers:
          # 1) runs afters pre_tasks
          # 2) this runs after roles and tasks
          # 3) runs after post_tasks
